### ISSUE TITLE
apply to exom sequence data

### ISSUE THREAD

**Issue by tlu0918** [WGLab/RepeatHMM#11]
Dear RepeatHMM

I have a question regarding RepeatHMM data on exome sequence data. I currently have exome sequence data genotyped with the Illumina HumanExome BeadChip and I would like estimate the counts of CAG repeat in chr4 HTT gene.  

Can I directly apply RepeatHMM to my exome data ? Or I should increase the dense of my data via imputation such as IMPUTE2 before the application? My data is in Plink bed format. Could you please suggest me a tool to covert to BAM format. Thanks!

Best,

Ake

**Comment by kaichop** [comment]
RepeatHMM is designed for PacBio/Nanopore data. It cannot handle your data.

**Comment by tlu0918** [comment]
Dear Kai

Thank you very much for your quick response. Hopefully we will have the data in the future to apply RepeatHMM. 

I have one more question. Can RepeatHMM be applied to a SAM file with FLAG field missing?

Thanks!

Ake

**Comment by liuqianhn** [comment]
Hi @tlu0918 , RepeatHMM uses standard SAM format. An input with no FLAG field might cause an error. An input with improper FLAG field would not cause an error and the results might be not guaranteed.  If re-alignment option is used, the improper FLAG field would have little effect since reads would be re-aligned.

**Comment by tlu0918** [comment]
Hi

Thank you so much for the clarification!

Best

Ake
