### ISSUE TITLE
Reproducibility Question

### ISSUE THREAD

**Issue by andyb3** [WGLab/RepeatHMM#12]
Hi. Thanks for making this great tool. We notice that when running the same BAM through repeatHMM multiple times, the repeat counts in the output can vary 
slightly each time. Which step(s) of the process introduce this variability and fo you know if there are any settings we can tweak so that we get reproducibile results?

Happy to share the commands we are using if that helps.

Thanks,
Andy

**Comment by liuqianhn** [comment]
Hi @andyb3 , thank you for being interested in our tool. Sorry for late reply. 

The slight difference would be caused by GaussianMixture for detecting peaks in a list with not very sharp peak of Gaussian distribution(For those distribution with a very clear peak, GaussianMixture generally gives a same peak detection each time).  GaussianMixture needs a random initialization and thus detects peaks with slight difference.  One way to avoid this difference would be to give a seed in random initialization. Feel free to let me know how this slight difference affect your analysis.  Thank you.

**Comment by andyb3** [comment]
Thanks for your response! That is very helpful. Is there a way to supply a seed to the GaussianMixture through the repeatHMM settings or would this require tweaking of the code?

**Comment by liuqianhn** [comment]
Hi @andyb3 , I am afraid that there is no parameter for this seed setting now. If you want to remove this difference, a simple way is to try to add seed setting (for example np.random.seed(1)) just after line 157 of bin/scripts/myGaussianMixtureModel.py. Feel free to let me know if it does not work and any feedback. Thank you.

**Comment by andyb3** [comment]
Ah OK. I will try that! Thanks again for your help. Question answered so I will close the issue.
