### ISSUE TITLE
Genes not in  hg*predefined.pa

### ISSUE THREAD

**Issue by Langna** [WGLab/RepeatHMM#16]
If you are interested in a region defined by yourself, you can (i) either add it in "bin/reference_sts/hg38/hg38.predefined.pa", or (ii) use "--UserDefinedRepeat chr/start_pos/end_pos/repeat_pattern/strand/range/others/" where the first five are necessary while the remain (range and others) could be empty.

Feel free to let me know if anything I can help.

_Originally posted by @liuqianhn in https://github.com/WGLab/RepeatHMM/issues/14#issuecomment-404010908_

**Comment by Langna** [comment]
@liuqianhn ， I am trying analysis the  gene ：SCA8、SCA17  which are not in file"bin/reference_sts/hg38/hg38.predefined.pa". The accuracy of results is obviously lower than the results of genes  predefined in “bin/reference_sts/hg38/hg38.predefined.pa”。what I added is：
”
atxn17,chr6,170561926,170562015,CAG,+30,,
atxn8,chr13,70139384,70139428,CTG,+15,,
“
Is there something wrong or what do I need to pay attention to？

**Comment by liuqianhn** [comment]
Hi @Langna , Thank you for being interested in our tool.

In a bam with hg38 alignment, For ATXN17, I would suggest "atxn17,chr6,170561907,170562025,CAG,+36,,", and for AXTN8, I would suggest "atxn8os,chr13,70139351,70139428,CTG,+15,16-37:110-250," since this repeat is mixed with "CTA".  It would be better to define the whole repeat region in the reference genome rather than part of repeats. 

Meanwhile, please make the reference genome using for bam files be same as that using in the hg*.predefined.pa. 

Feel free to let me know more if I can help.

**Comment by Langna** [comment]
It is ok after doing what you said.
