### ISSUE TITLE
How should I interpret the output?

### ISSUE THREAD

**Issue by c-zhou** [WGLab/RepeatHMM#2]
Hi there,

If I'm right, the file logbam/RepBAM_*.log contains all the information I need. Right? Then how should I interpret them? Especially for example these two lines,

_INFO:   p2bamhmm ['vntr_5', 362.46153846153845, [0, 0], 'allocr:219:1, 242:1, 259:1, 279:1, 281:1, 301:1, 305:1, 308:1,', 8, 45]
INFO:       p2sp ['vntr_5', 362.46153846153845, [0, 0], 'allocr:242:1, 259:1, 279:1, 281:1, 301:1, 305:1, 308:1,', 7, 10]_

**what does _p2bamhmm_ and _p2sp_ mean and how should I interpret the information in the square parentheses?**

Sometimes I got the line,

_INFO: Warning!!!! could not find optimized model_

**What does this line mean?**

I got them from the options, _python repeatHMM.py BAMinput  --hg _hgfile_ --Patternfile _patternfile_ --repeatName _repeatname_ --Onebamfile _bamfile_ --SeqTech Nanopore_

I have attached two output logs for your information. It would be greatly appreciated if you can add more explanations about the log file, such as lines like these,

_INFO: ref_repeat 362    GGGATAGTGTAGG   +357.2
INFO: no_repeat_id_list 43
INFO: short_repeat_id_list 0
INFO: repeat_id_list 0
INFO: expRegionInLongRead= 0 0
INFO: nonRepeatinLongRead= 7 10
INFO: tol_info=['', 0, 0]
INFO: allocr:242:1, 259:1, 279:1, 281:1, 301:1, 305:1, 308:1,_

Thank you very much.

[RepBAM_VNTR_5.gmm_GapCorrection1_FlankLength30_hg19_comp_Nanopore_I0.120_D0.020_S0.020.txt](https://github.com/WGLab/RepeatHMM/files/1175376/RepBAM_VNTR_5.gmm_GapCorrection1_FlankLength30_hg19_comp_Nanopore_I0.120_D0.020_S0.020.txt)
[RepBAM_VNTR_7.gmm_GapCorrection1_FlankLength30_hg19_comp_Nanopore_I0.120_D0.020_S0.020.txt](https://github.com/WGLab/RepeatHMM/files/1175378/RepBAM_VNTR_7.gmm_GapCorrection1_FlankLength30_hg19_comp_Nanopore_I0.120_D0.020_S0.020.txt)

**Comment by liuqianhn** [comment]
Hi Zhou, you are right. The results would be summarized at the end of logbam/RepBAM_*.log. p2sp's results are recommended which usually are better than p2bamhmm's results. p2bamhmm is a simple version of HMM without poorer accuracy and could be removed in future version. [XX, YY] is the estimated allele size, followed by a distribution of all estimated repeat sizes. I will add more explanation. Thanks.

> INFO: Warning!!!! could not find optimized model
 
Gaussian Mixture model is used in RepeatHMM to infer repeat count. Thus, enough reads are needed to support the estimation. From your output, it could be seen that each estimated repeat count was only detected from a single read. Gaussian Mixture model thus cannot find a better model to fit the data and give the warning. 

All the INFO below are for the DEBUG purpose, and they would not be in the output file with default settings.  

> INFO: ref_repeat 362 GGGATAGTGTAGG +357.2

The information of the GGGATAGTGTAGG repeat in the reference genome, and "+357.2" is the information provided by users or in pre-defined repeats.

> INFO: no_repeat_id_list 43

The number of reads whose repeats could not be detected by TRF (Tandem Repeat Finder).

> INFO: short_repeat_id_list 0

The number of reads whose repeats could be detected by TRF but the repeat regions are too short.

> INFO: repeat_id_list 0

The number of reads whose repeats could be detected by TRF.

> INFO: expRegionInLongRead= 0 0

The number of reads with longer repeat regions detected, followed by the number of reads without longer repeat regions or incorrectly aligned or partial alignment with the region of interest.

> INFO: nonRepeatinLongRead= 7 10

The number of reads with possibly short repeat regions detected, followed by the number of reads with incorrect alignment or partial alignment with the region of interest.

> INFO: tol_info=['', 0, 0]

The tolerant repeat patterns. For example, CTT could be considered to well match with CTG in the error correction process (not  in the HMM process), although the last alignment are T vs G. Here, not tolerant repeat patterns were specified. 

> INFO: allocr:242:1, 259:1, 279:1, 281:1, 301:1, 305:1, 308:1,

The dictionary of the estimation repeat count. In 'X:Y', 'X' is the estimation repeat count, and 'Y' is the number of supporting reads. 

Usually, high coverage would be a better choice to reliably detect much longer repeats (hundreds of repeats); otherwise, each estimation repeat count only has very few supporting reads, and RepeatHMM might filter the estimation at the final step, and just outputs something like [0, 0], indicating that there is not enough evidence to support the estimation.

**Comment by c-zhou** [comment]
That helps me a lot. Thank you very much liuqian.

**Comment by liuqianhn** [comment]
It is great that it is helpful.
