### ISSUE TITLE
undefined symbol: npy_fabsl

### ISSUE THREAD

**Issue by ghost** [WGLab/RepeatHMM#52]
I get the following error when trying to run 
python /RepeatHMM/RepeatHMM/bin/repeatHMM.py -h

`ImportError: /RepeatHMM/lib/python2.7/site-packages/hmmlearn/_hmmc.so: undefined symbol: npy_fabsl`

![1669107495(1)](https://user-images.githubusercontent.com/54733697/203270396-2ca87776-5b17-4183-a2f0-fc621c6c40f2.png)

**Comment by ghost** [comment]
Try running uninstalling the package and then run `pip install --no-cache-dir hmmlearn`
i still get the following error message 
![1669108576(1)](https://user-images.githubusercontent.com/54733697/203274366-317af380-2596-4bf8-8317-53871526ece6.png)

the RepeatHMM Software installation process: 
`source /miniconda/build/bin/activate

conda activate RepeatHMM

cd /RepeatHMM/RepeatHMM/bin/RepeatHMM_scripts/UnsymmetricPairAlignment/

make`

**Comment by liuqianhn** [comment]
@huangrongbioinfomation It is not an issue of install RepeatHMM script, but an issue to install hmmlearn. What you can try:
1. Uninstall hmmlearn first before try re-install with `--no-cache-dir`
2. Post an issue in hmmlearn to see how they solve it, since hmmlearn developers know better than me about this issue.
