### ISSUE TITLE
question about output

### ISSUE THREAD

**Issue by Tina9** [WGLab/RepeatHMM#6]
Hi there,

I want to find the minimum sequencing depth of RepeatHMM, so I used the same gene's sequence but with different depth of coverage. However, the output would be saved to the logfile with the same name. So I can't deal with the files in pitches.  

Names of my files are just like that "sca3.20_21", "sca3.148_149" and so on. How can I differ the output when I deal with the files in pitchies?

I think it is much better if you can add the input file's name before the output files' name or users can specify the output file name.

I will be appreciate for your help.

**Comment by liuqianhn** [comment]
Hi @Tina9, RepeatHMM already has an option of "--UserDefinedUniqID", which specifies a unique file name. By default, this option is None and thus was not used. You can use '--UserDefinedUniqID sca3.20_21' or '--UserDefinedUniqID sca3.148_149' for your examples. Please note that it would be better that the value of "--UserDefinedUniqID" does not contain such as ":", "\", "/" or "-".  Thanks.

**Comment by Tina9** [comment]
Thanks for your answer. Sorry for that I didn't found the option.
And I still have a qustion? How about threads? Can user specify the thread?  I found smaller the depth of coverage， and more time RepeatHMM needed. Is that normal?
Thanks for your help

**Comment by liuqianhn** [comment]
Hi @Tina9 , RepeatHMM does not support multi-threads right now. I will add the option later. Sorry for this. 

Regarding the running time of RepeatHMM, my experience is that for the same gene, the smaller the coverage is, the less time of RepeatHMM needed, when the coverages are significantly different. So, your issue surprised me. Please let me know more so that I can help this.

**Comment by Tina9** [comment]
Yes, I assumed the time consuming as your description after reading your paper.  However, it was completely reversed. Comparing to the depth of 28X with almost one and a half hour, the depth of 218X just spent one hour. It is strange ,right?  May be I should try more?
Thanks for your help again.

**Comment by liuqianhn** [comment]
Hi @Tina9 , you are welcome. The time consuming is strange to me. I have no idea about this right now. Please reopen the issue if you need other help.

**Comment by Tina9** [comment]
Hi Liu,
   I got different results when I used the same command line. For example, I used the same data input and same command. Sometimes RepeatHMM could get a result, but sometimes RepeatHMM could not. But if RepeatHMM could get the result, the results were the same. Is that normal? However, I am indeed not good at algorithm. I thonght the coverage might be the reason. But it affected nothing.
    I really need your help.

**Comment by liuqianhn** [comment]
Hi Tina, 
1. It is not normal. The same results should be obtained with the same data and the same settings. Do you mind deleting sensitive information, and sending your data (which generate different results) and commands to me so that I can find out the issues and fixed it? Thanks. 

2. When the repeat is not large, a certain coverage could generate correct results and much more coverage than that number might not be helpful. But when the repeat is very large, more coverage is needed to have correct results, and then the coverage is an important factor. In your analysis, what is the range of repeats?

**Comment by Tina9** [comment]
Could you please give me your email?

**Comment by liuqianhn** [comment]
Hi Tina, my email is liuqianhn@hotmail.com.  But a large file might not be sent by email. If your files are large, you can put them in a zip file, upload the zip file to dropbox and then send the URL to me. After I download it, you can delete it soon.

**Comment by Tina9** [comment]
OK， thank you so much.
